// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type Comment = { id: bigint, userId: bigint, user: User | null, parentId: bigint | null, text: string, createdDate: string, modifiedDate: string, replies: Array<Comment> | null, };
