// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowWithOrder } from "./FollowWithOrder";
import type { Highlight } from "./Highlight";
import type { JsonValue } from "./serde_json/JsonValue";

export type Content = { id: bigint, link: string, title: string, favorite: boolean, snippet: string | null, toRead: boolean | null, createdBy: bigint | null, createdDate: string, modifiedDate: string, lastCrawled: string | null, metadata: JsonValue | null, highlights: Array<Highlight>, userIds: Array<bigint> | null, savedBy: Array<FollowWithOrder> | null, };
