// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowingUser } from "./FollowingUser";

export type FollowWithOrder = { followingUser: FollowingUser, order: bigint, };
