// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";

export type Highlight = { id: bigint, userId: bigint, linkId: bigint, highlight: string, createdDate: string, leftContext: string, rightContext: string, rawHighlight: string, comment_ids: Array<bigint | null>, comment: Comment | null, };
