// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FollowingUser } from "./FollowingUser";

export type UserProfile = { id: bigint, firstName: string, lastName: string, userLink: string, major: string | null, interests: string | null, expertise: string | null, school: string | null, github: string | null, twitter: string | null, website: string | null, createdDate: string, modifiedDate: string, lastOnline: string, lastCheckedNotifications: string, views: bigint, numFollowers: bigint, followed: boolean | null, followingMe: boolean | null, recentUsers: Array<FollowingUser>, followingUsers: Array<FollowingUser>, };
